#!/usr/bin/env bash
#
# Build all configured libraries (and out-of-tree applications) and
# generate the compilation database, the .clangd configuration, and
# the version lock file.

set -euo pipefail

cd "$(dirname "$0")"

# shellcheck source=load_config.sh
. ./load_config.sh

case "$(basename "$COMPILE_DB")" in
  compile_commands.json) ;;
  *)
    echo "❌ COMPILE_DB must be named compile_commands.json (a compdb and clangd requirement): $COMPILE_DB"
    exit 1
    ;;
esac
if [ ! -d "$(dirname "$COMPILE_DB")" ]; then
  echo "❌ COMPILE_DB directory does not exist: $(dirname "$COMPILE_DB")"
  exit 1
fi
DBDIR="$(cd "$(dirname "$COMPILE_DB")" && pwd)"
COMPILE_DB="$DBDIR/$(basename "$COMPILE_DB")"

# The successful build ends by freezing the versions; verify up front
# that the libraries are clean enough to produce a reproducible lock,
# instead of failing after the whole rebuild.
./freeze_versions.sh --check

# Builds and tests need the installed tools and libraries.
export PATH="$PREFIX/bin:$PATH"
export LD_LIBRARY_PATH="$PREFIX/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"

# Generate .clangd next to the database so that clangd prefers the
# in-tree headers of this workspace over the installed copies, also
# for out-of-tree application sources below the same directory.
# clangd needs absolute paths here, so the file is generated locally
# instead of being committed.
{
  echo "# Generated by build_compile_commands.sh -- do not edit."
  echo "CompileFlags:"
  echo "  Remove: [-I$PREFIX/include]"
  echo "  Add:"
  for lib in $LIBS; do
    echo "    - -I$MILIB_ROOT/$lib/include"
  done
  echo "    - -I$PREFIX/include"
} > "$DBDIR/.clangd"

# Timestamp reference for the artifact freshness check below.
BUILD_STAMP="$(mktemp)"
trap 'rm -f "$BUILD_STAMP"' EXIT

make clean
bear --output "$COMPILE_DB" -- make

# Capture the out-of-tree application programs, after the libraries
# are installed. bear only records compilations that actually run, so
# clean each directory first.
for d in $APP_DIRS; do
  make -C "$d" clean || true
  bear --append --output "$COMPILE_DB" -- make -C "$d"
done

# Every configured C++ variant must have been produced by this very
# build; an older file means the tests above validated binaries that
# do not correspond to the checked-out sources.
for lib in $CPP_LIBS; do
  so="$PREFIX/lib/lib${lib}_cpp.so"
  if [ ! "$so" -nt "$BUILD_STAMP" ]; then
    echo "❌ C++ variant missing or stale (not produced by this build): $so"
    exit 1
  fi
done
# C++ variants nothing in the configuration accounts for are likely
# leftovers of an earlier setup; they are linked via <lib>-config
# -lcpp without ever being rebuilt.
for so in "$PREFIX"/lib/lib*_cpp.so; do
  if [ ! -e "$so" ]; then continue; fi
  name="$(basename "$so")"
  name="${name#lib}"
  name="${name%_cpp.so}"
  case " $CPP_LIBS $CUSTOM_LIB " in
    *" $name "*) ;;
    *) echo "⚠️ Unmanaged C++ variant in the prefix (stale leftover?): $so" ;;
  esac
done

# The C++ passes recompile the same sources with g++; keep a single
# entry per file (the gcc one) so clangd sees one canonical command.
jq 'group_by(.file)
    | map(if length > 1
          then ([ .[] | select((((.arguments // []) | join(" "))
                                + " " + (.command // ""))
                               | test("g\\+\\+") | not) ] as $kept
                | if ($kept | length) > 0 then $kept else . end)
          else . end)
    | add // []' "$COMPILE_DB" > "$COMPILE_DB.tmp"
mv "$COMPILE_DB.tmp" "$COMPILE_DB"

# Add header entries for clangd.
compdb -p "$DBDIR" list > "$COMPILE_DB.tmp"
mv "$COMPILE_DB.tmp" "$COMPILE_DB"

# Record the exact library versions this database was built from.
./freeze_versions.sh

# Local Variables:
# jinx-local-words: "clangd compdb config env json"
# End:
