#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"
ROOT="$(pwd)"
JSON="$ROOT/compile_commands.json"
PREFIX="${PREFIX:-$HOME/usr}"

# List of libraries
# shellcheck source=liblist
. ./liblist

# Generate .clangd so that clangd prefers the in-tree headers of this
# workspace over the installed copies. clangd needs absolute paths
# here, so the file is generated locally instead of being committed.
{
  echo "# Generated by build_compile_commands.sh -- do not edit."
  echo "CompileFlags:"
  echo "  Remove: [-I$PREFIX/include]"
  echo "  Add:"
  for lib in $LIBS; do
    echo "    - -I$ROOT/$lib/include"
  done
  echo "    - -I$PREFIX/include"
} > .clangd

make clean
bear -- make

# Add header entries for clangd.
compdb -p . list > "$JSON.tmp"
mv "$JSON.tmp" "$JSON"

# Record the exact library versions this database was built from.
for lib in $LIBS; do
  sha=$(git -C "$lib" rev-parse HEAD)
  branch=$(git -C "$lib" rev-parse --abbrev-ref HEAD)
  if [ -n "$(git -C "$lib" status --porcelain --untracked-files=no)" ]; then
    dirty=" dirty"
  else
    dirty=""
  fi
  echo "$lib $sha $branch$dirty"
done > versions.lock

# Local Variables:
# jinx-local-words: "clangd compat env json liblist sha shellcheck tmp usr"
# End:
