#!/usr/bin/env bash
#
# Generate a direnv .envrc that puts the configured install prefix on
# PATH and LD_LIBRARY_PATH. The file is written to ENVRC_DIR (empty =
# the directory containing PREFIX, e.g. PREFIX=<project>/.local gives
# <project>/.envrc).
#
# Usage:
#   ./gen_envrc.sh            # Write .envrc (refuses to overwrite)
#   ./gen_envrc.sh --force    # Overwrite an existing .envrc

set -euo pipefail

cd "$(dirname "$0")"

# shellcheck source=load_config.sh
. ./load_config.sh

FORCE=false
if [[ $# -gt 0 ]]; then
  case "$1" in
    --force|-f)
      FORCE=true
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--force]"
      exit 1
      ;;
  esac
fi

if ! command -v direnv >/dev/null 2>&1; then
  echo "⚠️ direnv is not installed; skipping (.envrc not written). See install_prereq.sh."
  exit 0
fi

DIR="${ENVRC_DIR:-$(dirname "$PREFIX")}"
if [ ! -d "$DIR" ]; then
  echo "❌ Target directory does not exist: $DIR (check ENVRC_DIR/PREFIX)"
  exit 1
fi
TARGET="$DIR/.envrc"
if [ -e "$TARGET" ] && ! $FORCE; then
  echo "⚠️ $TARGET already exists; rerun with --force to overwrite."
  exit 1
fi

{
  echo "# Generated by mi-lib gen_envrc.sh -- do not edit."
  echo "PATH_add \"$PREFIX/bin\""
  echo "path_add LD_LIBRARY_PATH \"$PREFIX/lib\""
} > "$TARGET"
echo "✅ Wrote $TARGET"
echo "💡 Run: direnv allow \"$DIR\""

# Local Variables:
# jinx-local-words: "config direnv env envrc"
# End:
